name: Deploy to Firebase
'on':
  push:
    branches:
      - master
env:
  REACT_APP_API_KEY: '${{ secrets.REACT_APP_API_KEY }}'
  REACT_APP_AUTH_DOMAIN: '${{ secrets.REACT_APP_AUTH_DOMAIN }}'
  REACT_APP_PROJECT_ID: '${{ secrets.REACT_APP_PROJECT_ID }}'
  REACT_APP_STORAGE_BUCKET: '${{ secrets.REACT_APP_STORAGE_BUCKET }}'
  REACT_APP_MESSAGING_SENDER_ID: '${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}'
  REACT_APP_ID: '${{ secrets.REACT_APP_ID }}'
jobs:
  bnd:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: CI=false npm run build
      - name: Deploy on Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TO_THE_LIST }}'
          channelId: live
          projectId: '${{ secrets.REACT_APP_PROJECT_ID }}'
